### ISSUE TITLE
Питання щодо питань на екзамен.

### ISSUE THREAD

**Issue by anxolerd** [HowProgrammingWorks/Letters#1]
Не зовсім зрозуміло, що Ви очікуєте прочитати/почути на екзамені по таких питаннях:
- № 33. Классификация языков программирования по уровню абстракции
- № 40. Классификация способов непрямого наследования
- № 47. Контексты и управление видимостью в контекстах
- № 48. Оптимизирующие компиляторы и их особенности
- № 53. Глобальное состояние и комбинаторный взрыв
- № 54. Способы минимизации глобального состояния
- № 57. Организация слоя доступа к данным
- № 58. Место кода бизнес-логики, интерфейсов и фреймворка в архитектуре ПО
- № 59. Экранирование модулей приложения друг от друга

Прохання вточнити ці питання. Також прохання додати до термінів їх англомовні варіанти, так як більшість матеріалів все ж англомовні, і наявність ангійської термінології полгшить пошук відповідних матеріалів.

**Comment by anxolerd** [comment]
@tshemsedinov [June, 08, 2016]

> **№47** это контекст функции, контекст модуля, глобальный контекст или контекст песочницы. общее понятие не завязано на js
> 
> **№ 48** имеется в виду понимание принципа, я это рассказывал на примере V8 и но статистический оптимизатор есть практически во всех виртуальных машинах. А в js есть специфика: скрытые классы, построение типизированных структур, массивов, справочников, списков по результатам анализа исполнения и динамическое порождение дженериков, то, что зовется обобщенное программироваие

**Comment by tshemsedinov** [comment]
- № 33. Классификация языков программирования по уровню абстракции  
  Вообще, классификаций есть несколько, например: микрокод, машинный код, ассемблеры, языки низкого уровня общего назначения (как C, C++, Pascal), языки высокого уровня общего назначения (C#, Java, Python, JavaScript), специализированные языки высокого уровня (как SQL, Matlab), узкоспециализированные языки DSL. Есть и другие классификации, мы обсуждали на лекциях несколько, но даже если Вы на экзамене сами проанализируете языки и построите классификацию исходя из своего опыта и понимания, то по ней я смогу оценить Ваш уровень.
- № 40. Классификация способов непрямого наследования  
  Мы рассматривали как минимум непрямое наследование через примеси, через события, через замыкания. Вообще их больше, но эти основные нужно уметь пояснить.
- № 47. Контексты и управление видимостью в контекстах  
  Имеется в виду контексты функций, модулей, глобальный контекст, песочницы. Порождение контекстов, управление контекстами на примере API виртуальной машины V8 или любой другой реализации.
- № 48. Оптимизирующие компиляторы и их особенности  
  Создание скрытых классов, статистическое определение типов, не явные дженерики, прогревание кода, например в V8, но подобные вещи происходят и при компиляции C/C++ и в других виртуальных машинах .Net, JVM.
- № 53. Глобальное состояние и комбинаторный взрыв  
  В чем проблема использования глобального состояния, почему все же есть возможность его использовать, что именно делать с ним хорошо, а что плохо и почему. Комбинаторный взрыв происходит при размещении структур данных в глобальном состоянии и обращении к ним из разных функций, классов и модулей, которые могут так его модифицировать, что обобщенный их результат не предсказуем, дает комбинаторный взрыв.
- № 54. Способы минимизации глобального состояния  
  Песочницы, замыкания, модули, экранирование модулей друг от друга, разделение состояния различными способами, например, переходя на взаимодействие через подписку событий, на контракты или абстрактные интерфейсы, на очереди запросов.
- № 57. Организация слоя доступа к данным  
  Зачем нужен слой доступа к данным DAL (data access layer), его задачи и эффект от использования.
- № 58. Место кода бизнес-логики, интерфейсов и фреймворка в архитектуре ПО  
  Код может относиться или к абстрактным алгоритмам, как сортировка, матметоды, шифрование, алгоритмы статистики и т.д., может относиться к модели предметной области, может относиться к организации пользовательского интерейса, а может относиться к API платформы (фреймворка), вот как определить, какой код к чему относится и не смешать его. Это слишком большая тема, чтобы я ее тут написал.
- № 59. Экранирование модулей приложения друг от друга  
  Как скрыть внутренности модуля, внутренние структуры данных и функции, например, при помощи ООП, песочниц и областей видимости, см. № 54

Я могу повторить многое на консультации, потому, что не все были на всех лекциях, я понимаю.

**Comment by GreatAndPowerfulKing** [comment]
Ще не зовсім зрозуміло питання "2. Обзор топологий компоновки программных компонентов". Якщо маються на увазі топології bus, star та circle, то як їх адаптувати до програмних модулів?

**Comment by tshemsedinov** [comment]
Да, имеются в виду топологии: звезда, кольцо, сеть, хаб, брокер, шина, дерево, полносвязная, звенья (параллельное и последовательное соединение). @GreatAndPowerfulKing по этому поводу была целая лекция, программные компоненты взаимодействуют в одной или нескольких топологиях (может быть смешанная или гибридная топология), мы выбираем это при разработке архитектуры. В полном объеме это ни где не взять, кроме той лекции, которую Вы пропустили, но могут помочь, например, вот эти ссылки:
- http://zguide.zeromq.org/page:all
- http://hpcc.kpi.ua/hpc-book/
- http://www.intuit.ru/studies/courses/641/497/lecture/11308

**Comment by GreatAndPowerfulKing** [comment]
Дякую!

**Comment by tshemsedinov** [comment]
Хвала Аллаху! Соблюдайте Рамадан и ведите себя прилично )))
