### ISSUE TITLE
KPI 2016 Summer: чат

### ISSUE THREAD

**Issue by firec0der** [HowProgrammingWorks/Letters#2]
Как я и говорил на встрече, нам нужен gitter (или любые другие варианты, но gitter предпочтительней, потому что есть интергация с github и адекватная подсветка кода) чат для совместной координации, обмена кодом, ссылками, etc.

**Comment by tshemsedinov** [comment]
https://gitter.im/nodeua/NodeJS?utm_source=share-link&utm_medium=link&utm_campaign=share-link
