### ISSUE TITLE
Стосовно заліку по предмету Парадігми програмування.

### ISSUE THREAD

**Issue by radetskyi** [HowProgrammingWorks/Letters#6]
@tshemsedinov, від студента групи зпі-зп62 Радецького О.М.
Минулої п'ятниці (10.02.2017) я отримав залік з дисципліни "ПП" (оцінка стоїть в заліковці).
Сьогодні мені повідомили що у відомості в мене відсутня будь-яка оцінка.
Де і як Вас можна знайти аби вирішити це питання?

**Comment by SerhiiBychok** [comment]
@tshemsedinov и скажите где можно найти ссылки "как красиво писать код", которые Вы обещали скинуть.

**Comment by tshemsedinov** [comment]
@gezellig буду в 18 корпусе в 8 комнате до 4:30 или завтра, я пока ведомости придержал, много не явившихся.

@SergeyBychok пришлю, я помню.

**Comment by radetskyi** [comment]
@tshemsedinov, завтра, о котрій і куди можна підійти?

**Comment by tshemsedinov** [comment]
Лучше на 3 пара или в 8 комнате, расписание тут: http://rozklad.kpi.ua/Schedules/ViewSchedule.aspx?v=54c094fe-fc37-4766-b7f3-d8af303cb843
@gezellig
